### ISSUE TITLE
Multi threading would be a nice idea.

### ISSUE THREAD

**Issue by abbishal** [shamimrezasohag/DSAT-DNSSecurityAnalysisTool#3]
**Is your feature request related to a problem? Please describe.**
first of all, It is a great approach  from the contributors. But I think it takes a lot of time. Specially doing analysis of big list of subdomains will be frustrating.

**Describe the solution you'd like**
It would be great if multi threading feature will be introduced. So, then it will try to use much more of the available resources and bandwidth. Which will help to analyze the list of subdomains quickly.

**Comment by shamimrezasohag** [comment]
That's another good observation. Thank you for that. I will get back to you with updates.

**Comment by shamimrezasohag** [comment]
Multi-threading is added.
