### ISSUE TITLE
Inputs and outputs should be filtered.

### ISSUE THREAD

**Issue by abbishal** [shamimrezasohag/DSAT-DNSSecurityAnalysisTool#4]
**Is your feature request related to a problem? Please describe.**
This script takes any arbitrary input, which isn't a good practice I think users may mistakenly give wrong file containing non-domain names but script will not check if it is similar/looks like domain names instead it will send it to the resolver directly. Another thing is output shows the records and records code even there is no record for it(Null). which makes it look like garbage data. 

**Describe the solution you'd like**
All the lines of input files should be filtered (using regex would be a nice option) and write into  output file only if record exist. Cause there is no need of output analyze of cname or a record if they aren't configured. It jsut make the output large and make it harder to see legit analisys results

**Comment by shamimrezasohag** [comment]
Valid concern, loved the observation, will look into this, and get back with updates.

**Comment by shamimrezasohag** [comment]
issue resolved.

**Comment by shamimrezasohag** [comment]
issue resolved.
